### PR TITLE
feat: fixes for release 1.0

### LINKED ISSUE #54: Can't apply kyverno policy
I'm encountering an issue when trying to deploy a plugin on an EKS cluster using Helm. The policy provided within the samples folder seems to be incompatible with the chart deployment. When I attempt to apply the policy with kubectl apply -f kyverno-policy.yaml, I receive the following error:
```
Error from server: error when creating "../kyvernov2/templates/kyverno-policy.yaml": admission webhook "validate-policy.kyverno.svc" denied the request: policy contains invalid variables: variable substitution failed for rule call-aws-signer-extension: variable images must match regex "request\.|element|elementIndex|@|images\.|image\.|([a-z_0-9]+\()[^{}]" or patterns [tlscerts* response*]
```
**Current Configuration:**

The plugin is deployed via [kyverno-notation-aws Helm Chart](https://github.com/nirmata/kyverno-notation-aws/tree/main/charts/kyverno-notation-aws).
Kyverno is deployed through the [kyverno Helm Chart](https://github.com/kyverno/kyverno/tree/main/charts/kyverno).

**Policy Configuration:**
The policy I am applying is the kyverno-policy.yaml provided in the samples folder:
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-images     
spec:
  validationFailureAction: Enforce
  failurePolicy: Fail
  webhookTimeoutSeconds: 30
  schemaValidation: false
  rules:
  - name: call-aws-signer-extension
    match:
      any:
      - resources:
          namespaces:
          - test-notation
          kinds:
          - Pod
          operations:
            - CREATE
            - UPDATE
    context:
    - name: tlscerts
      apiCall:
        urlPath: "/api/v1/namespaces/kyverno-notation-aws/secrets/svc.kyverno-notation-aws.svc.tls-pair"
        jmesPath: "base64_decode( data.\"tls.crt\" )"
    - name: response
      apiCall:
        method: POST
        data:
        - key: images
          value: "{{images}}"
        - key: trustPolicy
          value: "tp-{{request.namespace}}"
        - key: attestations
          value: 
          - imageReference: "*"
            type: 
            - name: sbom/example
              conditions:
                all:
                - key: \{{creationInfo.licenseListVersion}}
                  operator: Equals
                  value: "3.17"
                  message: invalid license version
        service:
          url: https://svc.kyverno-notation-aws/checkimages
          caBundle: '{{ tlscerts }}'
    mutate:
      foreach:
      - list: "response.results"
        patchesJson6902: |-
            - path: {{ element.path }}
              op: replace
              value: {{ element.image }}
```
**Additional Information:**

The policy deployment works without a problem when I deploy both kyverno and the plugin manually, following the instructions provided [here](https://github.com/nirmata/kyverno-notation-aws/tree/main#install).
However, it fails when both are deployed via Helm. Is this a version issue or an issue with the policy?

### LINKED ISSUE #56: Image validation exeption in policy
Good day,
Is it possible to configure that policy validates images only from specific registries, but not all images? Currently seems like {{images}} variable have all images of pod, including init images. In my case I use for container image - signed image, but init images are from public registries and plugin returns error: 
```
2023-10-12T09:10:56.858Z	ERROR	verifier/verify.go:326	verification failed for image {{docker.io docker docker dind } /spec/containers/1/image}: failed to resolve digest: failed to resolve digest: HEAD "https://registry-1.docker.io/v2/docker/manifests/dind": GET "https://auth.docker.io/token?scope=repository%3Adocker%3Apull&service=registry.docker.io": response status code 401: Unauthorized

2023-10-12T09:10:56.859Z	ERROR	verifier/verify.go:110	failed to verify container docker: failed to verify image {{docker.io docker docker dind } /spec/containers/1/image}: failed to resolve digest: failed to resolve digest: HEAD "https://registry-1.docker.io/v2/docker/manifests/dind": GET "https://auth.docker.io/token?scope=repository%3Adocker%3Apull&service=registry.docker.io": response status code 401: Unauthorized

2023-10-12T09:10:56.859Z	ERROR	verifier/response.go:76	Verification failed with error failed to verify container docker: failed to verify image {{docker.io docker docker dind } /spec/containers/1/image}: failed to resolve digest: failed to resolve digest: HEAD "https://registry-1.docker.io/v2/docker/manifests/dind": GET "https://auth.docker.io/token?scope=repository%3Adocker%3Apull&service=registry.docker.io": response status code 401: Unauthorized

2023-10-12T09:10:57.525Z	INFO	verifier/client.go:188	Request recieved with data={Images:{InitContainers:map[] Containers:map[rbac-manager:{ImageInfo:{Registry:quay.io Name:rbac-manager Path:reactiveops/rbac-manager Tag:v1.6.5 Digest:} Pointer:/spec/template/spec/containers/0/image}] EphemeralContainers:map[]} TrustPolicy:aws-signer-trust-policy Attestations:[]}

2023-10-12T09:10:57.525Z	INFO	notationfactory/client.go:91	Using trust policy provided in the request aws-signer-trust-policy
```

### LINKED ISSUE #57: Controller Does Not Return Image Digest if Trust Policy is Set to Skip signatureVerification for a Registry
Scenario: I have a multi-container Pod with a main container and two init containers which are injected by another controller. I only want to validate the signature of the main container, which I signed with the Notation AWS Signer plugin. I configured the trust policy to skip verification of the other two containers by adding an additional trust policy block which had their registries set and `signatureVerifcation` set to level: skip.  When the controller finishes signature checking it returns a results object with the 3 containers, and only the container that was checked is returned with the digest, the other two only with the tag.

This causes downstream issues with the mutate block of the cluster policy, because you cannot mutate back to an image tag or the admission controller fails validation. 

Using: v1rc-1

### PR DESCRIPTION
**Pull request by vishal-chdhry**
## Explanation
Closes #54 
Closes #56
Closes #57 

This PR adds an option called imageReferences that can be used to specify which images to verify

### CODE REVIEW

File: auth.go [hunk 1]
```diff
@@ -36,13 +37,27 @@ func getRegion(registry string) (string, error) {
 	return ecrRegion, nil
 }
 
-func getAuthFromIRSA(ctx context.Context, ref registry.Reference) (authn.AuthConfig, error) {
+func filterAWSImages(image string) bool {
```
Comment (JimBugwadia) [inline auth.go:40]: @vishal-chdhry - I am not sure why this is necessary. We should be able to support images signed with notation and AWS signer but stored in registries other than ECR.

**Review by JimBugwadia — CHANGES_REQUESTED** [review]

File: auth.go (hunk 1 above)
Comment (vishal-chdhry) [reply auth.go:40]: @JimBugwadia It is possible that someone is using an image like busybox/nginx for init containers, notation will try to verify those and fail

Besides, verification of images outside of ECR + AWS Signer context can be done using kyverno and I dont think it will be any helpful to try to verify them here as this focusses on AWS signer and ECR

Comment (JimBugwadia) [reply auth.go:40]: @vishal-chdhry the question is on images signed by notation and the signer binary, but stored in registries other than ECR. Those cannot be verified without the extension.

Comment (vishal-chdhry) [reply auth.go:40]: @JimBugwadia , we can add a field for matching image references like to filter images instead of making it strict

**Comment by JimBugwadia** [comment]
@vishal-chdhry - that sounds good. 

Should we add a imageReferences and skipImageReferences fields as variables in the policy that are passed to the extension?

Or can we get this from the configured TrustPolicy CR?

**Comment by vishal-chdhry** [comment]
Yes we can configure trust policies to skip images that don't match.

And if the goal is to only mutate digests for verified image ( since Kyverno covers the other scenarios) then this change is not needed.

**Comment by JimBugwadia** [comment]
> And if the goal is to only mutate digests for verified image ( since Kyverno covers the other scenarios) then this change is not needed.

So, the user would use 2 policies? Something like this:
1. first policy: configure the TrustPolicy to only match images signed by notation & signer and mutate their digests
2. second policy: match everything else and use `required`, `verifyDigests`, `mutateDigests`, and `skipImageReferences` to cover the rest of the images

Can you create samples for how to achieve this for the use case mentioned in https://github.com/nirmata/kyverno-notation-aws/issues/57? We can add that to the docs, as it seems to be a fairly common use case.

**Comment by vishal-chdhry** [comment]
So, the user would use 2 policies? Something like this:
1. For the first policy they will match and verify images based notation trust policy. The images that are skipped during verification will not be mutated. 
2. A kyverno policy that fetches and mutates digests.

> Can you create samples for how to achieve this for the use case mentioned in https://github.com/nirmata/kyverno-notation-aws/issues/57? We can add that to the docs, as it seems to be a fairly common use case.
Sure

>  seems like we may still meed to change the response to indicate which images have been skipped, so we do not create a patch for those.

Adding a change where patch is not created if the image is skipped.

**Comment by vishal-chdhry** [comment]
@JimBugwadia Even if the trust policy filters image, we will still need to filter images since artifact reference must contain a digest, therefore we have have to resolve the digest before passing it to notation. Therefore we will try to resolve digest of every image and we will fail for those images that cannot be accessed by kyverno-notation-aws

**Review by JimBugwadia — APPROVED** [review]
